# Generated by Django 6.0.5 on 2026-05-15 13:54

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Adres",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kraj", models.CharField(max_length=100)),
                ("miasto", models.CharField(max_length=100)),
                ("ulica", models.CharField(max_length=255)),
                ("kod_pocztowy", models.CharField(max_length=6)),
                ("numer_budynku", models.CharField(max_length=10)),
                (
                    "numer_lokalu",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
            ],
            options={
                "verbose_name": "Adres",
                "verbose_name_plural": "Adresy",
            },
        ),
        migrations.CreateModel(
            name="Kategoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazwa", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Kategoria",
                "verbose_name_plural": "Kategorie",
            },
        ),
        migrations.CreateModel(
            name="Aukcja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazwa_produktu", models.CharField(max_length=200)),
                (
                    "cena_wywolawcza",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.0)]
                    ),
                ),
                ("data_wystawienia", models.DateField(auto_now_add=True)),
                ("data_zakonczenia", models.DateField()),
                ("opis", models.TextField(blank=True, max_length=1500)),
                (
                    "status",
                    models.CharField(
                        choices=[("Aktywny", "Aktywny"), ("Zakonczone", "Zakonczone")],
                        default="Aktywny",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="default/no-image-icon.png", upload_to="auction_image"
                    ),
                ),
                ("slug", models.SlugField(blank=True)),
                (
                    "kategoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kategorie",
                        to="serwis.kategoria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aukcja",
                "verbose_name_plural": "Aukcje",
            },
        ),
        migrations.CreateModel(
            name="ProfilUzytkownika",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rola",
                    models.CharField(
                        choices=[("Klient", "Klient"), ("Pracownik", "Pracownik")],
                        default="Klient",
                        max_length=20,
                    ),
                ),
                (
                    "uzytkownik",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Profil Użytkownika",
                "verbose_name_plural": "Profile Użytkowników",
            },
        ),
        migrations.CreateModel(
            name="Uzytkownik",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telefon", models.CharField(blank=True, max_length=11)),
                ("data_rejestracji", models.DateField(default=datetime.date.today)),
                (
                    "adres",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uzytkownicy",
                        to="serwis.adres",
                    ),
                ),
                (
                    "uzytkownik",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Użytkownik",
                "verbose_name_plural": "Użytkownicy",
            },
        ),
        migrations.CreateModel(
            name="Platnosc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status_platnosci",
                    models.CharField(
                        choices=[
                            ("Zaplacone", "Zaplacone"),
                            ("Anulowano", "Anulowano"),
                            ("Nie Zaplacone", "Nie Zaplacone"),
                        ],
                        default="Nie Zaplacone",
                    ),
                ),
                ("cena_koncowa", models.FloatField()),
                (
                    "metoda_platnosc",
                    models.CharField(
                        choices=[("Karta", "Karta"), ("Gotowka", "Gotowka")]
                    ),
                ),
                ("data_platnosc", models.DateTimeField(blank=True, null=True)),
                (
                    "aukcja",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="platnosci",
                        to="serwis.aukcja",
                    ),
                ),
                (
                    "platnik",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dokonane_platnosci",
                        to="serwis.uzytkownik",
                    ),
                ),
            ],
            options={
                "verbose_name": "Płatność",
                "verbose_name_plural": "Płatności",
            },
        ),
        migrations.CreateModel(
            name="Oferta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("oferowana_cena", models.FloatField()),
                ("data_zlozenia_oferty", models.DateTimeField(auto_now_add=True)),
                (
                    "aukcja",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oferty",
                        to="serwis.aukcja",
                    ),
                ),
                (
                    "kupujacy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zlozone_oferty",
                        to="serwis.uzytkownik",
                    ),
                ),
            ],
            options={
                "verbose_name": "Oferta",
                "verbose_name_plural": "Oferty",
            },
        ),
        migrations.AddField(
            model_name="aukcja",
            name="sprzedajacy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aukcje",
                to="serwis.uzytkownik",
            ),
        ),
    ]
