# Generated by Django 6.0.5 on 2026-05-16 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("serwis", "0002_alter_oferta_kupujacy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aukcja",
            name="status",
            field=models.CharField(
                choices=[
                    ("Aktywny", "Aktywny"),
                    ("Zakonczone", "Zakonczone"),
                    ("Wycofana", "Wycofana"),
                ],
                default="Aktywny",
            ),
        ),
        migrations.AlterField(
            model_name="oferta",
            name="aukcja",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="oferty",
                to="serwis.aukcja",
            ),
        ),
    ]
