# Generated by Django 6.0.5 on 2026-05-16 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("serwis", "0003_alter_aukcja_status_alter_oferta_aukcja"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aukcja",
            name="status",
            field=models.CharField(
                choices=[("Aktywny", "Aktywny"), ("Zakonczone", "Zakonczone")],
                default="Aktywny",
            ),
        ),
        migrations.AlterField(
            model_name="platnosc",
            name="metoda_platnosc",
            field=models.CharField(
                blank=True,
                choices=[("Karta", "Karta"), ("Gotowka", "Gotowka")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="platnosc",
            name="status_platnosci",
            field=models.CharField(
                choices=[
                    ("Zaplacone", "Zaplacone"),
                    ("Anulowano", "Anulowano"),
                    ("Nie Zaplacone", "Nie Zaplacone"),
                ],
                default="Nie Zaplacone",
                max_length=50,
            ),
        ),
    ]
