# Generated by Django 6.0.3 on 2026-05-07 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sklep_aplikacja", "0002_produkt_data_dodania"),
    ]

    operations = [
        migrations.AddField(
            model_name="produkt",
            name="obrazek",
            field=models.ImageField(blank=True, null=True, upload_to="produkty/"),
        ),
    ]
