# Generated by Django 6.0.5 on 2026-05-08 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sklep_aplikacja", "0003_produkt_obrazek"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produkt",
            name="data_dodania",
        ),
        migrations.RemoveField(
            model_name="produkt",
            name="obrazek",
        ),
        migrations.AddField(
            model_name="produkt",
            name="slug",
            field=models.SlugField(blank=True, max_length=180),
        ),
    ]
