# Generated by Django 6.0.5 on 2026-05-07 13:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_produktu', models.CharField(max_length=150)),
                ('opis', models.TextField(blank=True)),
                ('cena_produktu', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('stan_magazynowy', models.PositiveIntegerField(default=0)),
                ('czy_aktywny', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefon', models.CharField(blank=True, max_length=30)),
                ('ulica', models.CharField(blank=True, max_length=150)),
                ('miasto', models.CharField(blank=True, max_length=100)),
                ('kod_pocztowy', models.CharField(blank=True, max_length=20)),
                ('uzytkownik', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfilUzytkownika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rola', models.CharField(choices=[('klient', 'Klient'), ('pracownik', 'Pracownik')], default='klient', max_length=20)),
                ('uzytkownik', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Zamowienie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_zamowienia', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('nowe', 'Nowe'), ('oplacone', 'Opłacone'), ('wyslane', 'Wysłane'), ('zrealizowane', 'Zrealizowane'), ('anulowane', 'Anulowane')], default='nowe', max_length=20)),
                ('adres_dostawy', models.CharField(max_length=255)),
                ('wartosc_zamowienia', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zamowienia', to='sklep_aplikacja.klient')),
            ],
        ),
        migrations.CreateModel(
            name='PozycjaZamowienia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilosc', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('cena_jednostkowa', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('produkt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sklep_aplikacja.produkt')),
                ('zamowienie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pozycje', to='sklep_aplikacja.zamowienie')),
            ],
        ),
    ]
