# Generated by Django 6.0.3 on 2026-05-07 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sklep_aplikacja", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="produkt",
            name="data_dodania",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
