# Generated by Django 6.0.5 on 2026-05-08 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "sklep_aplikacja",
            "0004_remove_produkt_data_dodania_remove_produkt_obrazek_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="produkt",
            name="slug",
            field=models.SlugField(blank=True, max_length=180, unique=True),
        ),
    ]
