# Generated by Django 6.0.5 on 2026-05-09 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sklep_aplikacja", "0005_alter_produkt_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Kategoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazwa", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="produkt",
            name="kategoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="produkty",
                to="sklep_aplikacja.kategoria",
            ),
        ),
    ]
